version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book-sv
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my-network
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: book-sv
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - "3307:3306"
    networks:
      - my-network
  rabbitmq:
    image: rabbitmq:3.8.22
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
